export const ImagesGlobal = {
  LogoPrimary: require("../../assets/images/logo_primary.png"),
  IconHome: require("../../assets/images/home.png"),
  IconHomeSelected: require("../../assets/images/home_selected.png"),
  IconDebitCard: require("../../assets/images/debit_card.png"),
  IconDebitCardSelected: require("../../assets/images/debit_card_selected.png"),
  IconPayments: require("../../assets/images/payments.png"),
  IconPaymentsSelected: require("../../assets/images/payments_selected.png"),
  IconCredit: require("../../assets/images/credit.png"),
  IconCreditSelected: require("../../assets/images/credit_selected.png"),
  IconProfile: require("../../assets/images/profile.png"),
  IconProfileSelected: require("../../assets/images/profile_selected.png"),
  IconShow: require("../../assets/images/show.png"),
  IconHide: require("../../assets/images/hide.png"),
  IconCardBrandAspire: require("../../assets/images/card_brand_aspire.png"),
  IconCardNetworkVisa: require("../../assets/images/card_network_visa.png"),
  IconMenuDebitTopUp: require("../../assets/images/menu_debit_topup.png"),
  IconMenuDebitWeekly: require("../../assets/images/menu_debit_weekly.png"),
  IconMenuDebitFreeze: require("../../assets/images/menu_debit_freeze.png"),
  IconMenuDebitGetANew: require("../../assets/images/menu_debit_get_a_new.png"),
  IconMenuDebitDeactivate: require("../../assets/images/menu_debit_deactivate.png"),
};
